"""add flexible booking fields and constraint

Revision ID: 26b27b54e86b
Revises: ca8c3b832bac
Create Date: 2026-01-04 02:06:26.797092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b27b54e86b'
down_revision: Union[str, Sequence[str], None] = 'ca8c3b832bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('min_booking_duration_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False))
    op.add_column('rooms', sa.Column('booking_step_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'booking_step_minutes')
    op.drop_column('rooms', 'min_booking_duration_minutes')
    # ### end Alembic commands ###
