"""add file model

Revision ID: 611bc844e006
Revises: 3a2c1b9d7e6f
Create Date: 2026-01-07 01:48:25.016309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611bc844e006'
down_revision: Union[str, Sequence[str], None] = '3a2c1b9d7e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rooms_image_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rooms_image_id_fkey'), 'rooms', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
