"""some adds

Revision ID: ca8c3b832bac
Revises: 2853af1be9f8
Create Date: 2025-12-27 17:40:02.494309

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ca8c3b832bac'
down_revision: Union[str, Sequence[str], None] = '2853af1be9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    imagetype = postgresql.ENUM("ROOM", "LOCATION", name="pet1_imagetype", create_type=False)
    featuretype = postgresql.ENUM("ROOM", "LOCATION", name="pet1_featuretype", create_type=False)
    roomtype = postgresql.ENUM(
        "MEETING_ROOM",
        "COWORK_DESK",
        "STUDIO",
        "SPORT",
        name="pet1_roomtype",
        create_type=False,
    )
    timeslottype = postgresql.ENUM("FLEXIBLE", "FIXED", name="pet1_timeslottype", create_type=False)
    bind = op.get_bind()
    imagetype.create(bind, checkfirst=True)
    featuretype.create(bind, checkfirst=True)
    roomtype.create(bind, checkfirst=True)
    timeslottype.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image1x', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image2x', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', imagetype, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('type', featuretype, nullable=False),
    sa.CheckConstraint("\n            (\n              type = 'ROOM'\n              AND room_id IS NOT NULL\n              AND location_id IS NULL\n            )\n            OR\n            (\n              type = 'LOCATION'\n              AND location_id IS NOT NULL\n              AND room_id IS NULL\n            )\n            ", name='ck_features_type_matches_fk'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('type', roomtype, nullable=True))
    op.add_column('rooms', sa.Column('image_id', sa.Integer(), nullable=True))
    op.add_column(
        'rooms',
        sa.Column(
            'time_slot_type',
            timeslottype,
            nullable=False,
            server_default=sa.text("'FLEXIBLE'"),
        ),
    )
    op.add_column(
        'rooms',
        sa.Column(
            'hour_price',
            sa.DECIMAL(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.create_foreign_key(None, 'rooms', 'images', ['image_id'], ['id'])
    op.execute("UPDATE rooms SET time_slot_type = 'FLEXIBLE' WHERE time_slot_type IS NULL")
    op.execute("UPDATE rooms SET hour_price = 0 WHERE hour_price IS NULL")
    op.alter_column('rooms', 'time_slot_type', server_default=None)
    op.alter_column('rooms', 'hour_price', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'hour_price')
    op.drop_column('rooms', 'time_slot_type')
    op.drop_column('rooms', 'image_id')
    op.drop_column('rooms', 'type')
    op.drop_table('features')
    op.drop_table('images')
    bind = op.get_bind()
    postgresql.ENUM("FLEXIBLE", "FIXED", name="pet1_timeslottype").drop(bind, checkfirst=True)
    postgresql.ENUM(
        "MEETING_ROOM",
        "COWORK_DESK",
        "STUDIO",
        "SPORT",
        name="pet1_roomtype",
    ).drop(bind, checkfirst=True)
    postgresql.ENUM("ROOM", "LOCATION", name="pet1_featuretype").drop(bind, checkfirst=True)
    postgresql.ENUM("ROOM", "LOCATION", name="pet1_imagetype").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
